blog/urls.py
from django.urls import path
from .views import BlogDetailView, BlogListView

app_name = "blog"
urlpatterns = [
    path('<slug>/', BlogDetailView.as_view(), name = 'detail'),
    path('', BlogListView.as_view(), name = 'index'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from home.views import changeLang

urlpatterns = [
    path('chlang', changeLang, name='chlang'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('l/', include('landing.urls')),
    path('', include('home.urls')),
)

# uploaded files for develop stage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home

app_name = "home"
urlpatterns = [
    path('', home, name='home' ),
]

landing/urls.py
from django.urls import path
from .views import LandingDetailView, LandingListView

app_name = "landing"
urlpatterns = [
    path('<slug>/', LandingDetailView.as_view(), name = 'detail'),
    path('', LandingListView.as_view(), name = 'index'),
]

portfolio/urls.py
from django.urls import path
from .views import PortfolioListView, PortfolioDetailView

app_name = "portfolio"
urlpatterns = [
    path('<slug>/', PortfolioDetailView.as_view(), name = 'detail'),
    path('', PortfolioListView.as_view(), name = 'index'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.utils.translation import activate

# Language change toggle
def changeLang(request):
    activate(request.GET.get('lang'))
    return redirect(request.GET.get('next'))

# Home index view
def home(request):
    context = None
    return render(request, 'home/home.html', context)

home/templates/home/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html lang="fa" dir="rtl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}
            {% translate "Orso" %}
            {% endblock title %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block styles %}
            <link rel="stylesheet" href="{% static 'home/css/main.css' %}">
            {% if LANGUAGE_CODE == 'fa' %}
                <link rel="stylesheet" href="{% static 'home/css/rtl.css' %}">
            {% endif %}
        {% endblock styles %}
    </head>
    <body>
        <div>
            <a href="{% url 'chlang' %}?lang=en&next=/en/{{ request.path|slice:'4:' }}">{% translate "En" %}</a>
            / 
            <a href="{% url 'chlang' %}?lang=fa&next=/fa/{{ request.path|slice:'4:' }}">{% translate "Fa" %}</a>
        </div><hr>
        <a href="{% url 'home:home' %}"> {% translate "home" %} </a> |
        <a href="{% url 'blog:index' %}"> {% translate "blog" %} </a> |
        <a href="{% url 'portfolio:index' %}"> {% translate "portfolio" %} </a> |
        <a href="{% url 'landing:index' %}"> {% translate "landings" %} </a>

        <hr>
        {% block content %}
        {% endblock content %}
        
        {% block scripts %}
            <script src="" async defer></script>
        {% endblock scripts %}
        <hr>
        {{ LANGUAGE_CODE }}
        <br>
        {{ request.path }}
    </body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load i18n %}

{% block title %}
{% translate "home" %}
{% endblock title %}



{% block content %}
{% translate "Orso" %}
{% endblock content %}